// ╔══════════════════════════════════════════════════════╗
// ║  SCORE GUARDIANS — Archivo de Datos Clausura 2026    ║
// ║  Este es el ÚNICO archivo que necesitas actualizar    ║
// ║                                                       ║
// ║  Cómo actualizar:                                     ║
// ║  1. Abre la página web en tu navegador                ║
// ║  2. Haz clic en el logo → ingresa la contraseña       ║
// ║  3. Agrega resultados en el panel de Admin            ║
// ║  4. Presiona "Exportar JSON"                          ║
// ║  5. Reemplaza SOLO este archivo con el descargado     ║
// ╚══════════════════════════════════════════════════════╝

// ══════════════════════════════════════════
// PARTIDOS JUGADOS — Clausura 2026
// Actualizado hasta: Jornada 13 (05/abr/26)
// ══════════════════════════════════════════
const C2026 = [
{round:1,date:'09/ene/26',home:'Mazatlán',hg:1,ag:2,away:'FC Juárez'},
{round:1,date:'09/ene/26',home:'Pachuca',hg:0,ag:2,away:'Guadalajara'},
{round:1,date:'09/ene/26',home:'Toluca',hg:1,ag:0,away:'Monterrey'},
{round:1,date:'10/ene/26',home:'Cruz Azul',hg:0,ag:1,away:'Tigres'},
{round:1,date:'10/ene/26',home:'América',hg:0,ag:1,away:'Necaxa'},
{round:1,date:'10/ene/26',home:'León',hg:2,ag:0,away:'Querétaro'},
{round:1,date:'11/ene/26',home:'Santos',hg:0,ag:2,away:'Atlas'},
{round:1,date:'11/ene/26',home:'Tijuana',hg:0,ag:1,away:'Pumas'},
{round:1,date:'12/ene/26',home:'Atl. San Luis',hg:0,ag:2,away:'Puebla'},
{round:2,date:'16/ene/26',home:'Tigres',hg:1,ag:0,away:'Santos'},
{round:2,date:'16/ene/26',home:'FC Juárez',hg:1,ag:1,away:'Cruz Azul'},
{round:2,date:'16/ene/26',home:'Guadalajara',hg:2,ag:0,away:'Tijuana'},
{round:2,date:'17/ene/26',home:'Pumas',hg:2,ag:1,away:'Mazatlán'},
{round:2,date:'17/ene/26',home:'Monterrey',hg:1,ag:2,away:'América'},
{round:2,date:'17/ene/26',home:'Puebla',hg:0,ag:0,away:'León'},
{round:2,date:'18/ene/26',home:'Atlas',hg:1,ag:1,away:'Toluca'},
{round:2,date:'18/ene/26',home:'Querétaro',hg:0,ag:3,away:'Pachuca'},
{round:2,date:'18/ene/26',home:'Necaxa',hg:2,ag:1,away:'Atl. San Luis'},
{round:3,date:'23/ene/26',home:'Cruz Azul',hg:3,ag:1,away:'Santos'},
{round:3,date:'23/ene/26',home:'Toluca',hg:3,ag:0,away:'Pumas'},
{round:3,date:'23/ene/26',home:'América',hg:2,ag:0,away:'FC Juárez'},
{round:3,date:'24/ene/26',home:'Mazatlán',hg:0,ag:0,away:'Querétaro'},
{round:3,date:'24/ene/26',home:'Tijuana',hg:0,ag:1,away:'Monterrey'},
{round:3,date:'24/ene/26',home:'Atl. San Luis',hg:1,ag:0,away:'Tigres'},
{round:3,date:'25/ene/26',home:'Pachuca',hg:1,ag:1,away:'Necaxa'},
{round:3,date:'25/ene/26',home:'León',hg:1,ag:1,away:'Atlas'},
{round:3,date:'26/ene/26',home:'Puebla',hg:1,ag:2,away:'Guadalajara'},
{round:4,date:'30/ene/26',home:'FC Juárez',hg:3,ag:4,away:'Cruz Azul'},
{round:4,date:'30/ene/26',home:'Santos',hg:0,ag:1,away:'Toluca'},
{round:4,date:'31/ene/26',home:'Pumas',hg:1,ag:0,away:'León'},
{round:4,date:'31/ene/26',home:'Querétaro',hg:1,ag:1,away:'Tijuana'},
{round:4,date:'31/ene/26',home:'Monterrey',hg:2,ag:1,away:'Pachuca'},
{round:4,date:'01/feb/26',home:'Guadalajara',hg:3,ag:1,away:'Atl. San Luis'},
{round:4,date:'01/feb/26',home:'Tigres',hg:2,ag:1,away:'América'},
{round:4,date:'01/feb/26',home:'Necaxa',hg:1,ag:1,away:'Mazatlán'},
{round:4,date:'02/feb/26',home:'Atlas',hg:2,ag:1,away:'Puebla'},
{round:5,date:'06/feb/26',home:'Cruz Azul',hg:2,ag:0,away:'Querétaro'},
{round:5,date:'06/feb/26',home:'Toluca',hg:2,ag:1,away:'Guadalajara'},
{round:5,date:'07/feb/26',home:'León',hg:1,ag:2,away:'Tijuana'},
{round:5,date:'07/feb/26',home:'Puebla',hg:1,ag:2,away:'Santos'},
{round:5,date:'07/feb/26',home:'Atl. San Luis',hg:2,ag:1,away:'FC Juárez'},
{round:5,date:'07/feb/26',home:'Pachuca',hg:1,ag:0,away:'Pumas'},
{round:5,date:'08/feb/26',home:'América',hg:1,ag:1,away:'Atlas'},
{round:5,date:'08/feb/26',home:'Mazatlán',hg:0,ag:2,away:'Monterrey'},
{round:5,date:'09/feb/26',home:'Necaxa',hg:0,ag:1,away:'Tigres'},
{round:6,date:'13/feb/26',home:'Querétaro',hg:1,ag:2,away:'Santos'},
{round:6,date:'13/feb/26',home:'Guadalajara',hg:2,ag:1,away:'Cruz Azul'},
{round:6,date:'14/feb/26',home:'Pumas',hg:0,ag:0,away:'América'},
{round:6,date:'14/feb/26',home:'Atlas',hg:2,ag:2,away:'Atl. San Luis'},
{round:6,date:'14/feb/26',home:'Tijuana',hg:1,ag:3,away:'Toluca'},
{round:6,date:'14/feb/26',home:'Monterrey',hg:1,ag:2,away:'León'},
{round:6,date:'15/feb/26',home:'Tigres',hg:3,ag:1,away:'Pachuca'},
{round:6,date:'15/feb/26',home:'Santos',hg:2,ag:0,away:'Necaxa'},
{round:6,date:'16/feb/26',home:'FC Juárez',hg:1,ag:1,away:'Mazatlán'},
{round:7,date:'20/feb/26',home:'Cruz Azul',hg:1,ag:0,away:'Pumas'},
{round:7,date:'20/feb/26',home:'Toluca',hg:3,ag:1,away:'Atlas'},
{round:7,date:'21/feb/26',home:'América',hg:2,ag:0,away:'Guadalajara'},
{round:7,date:'21/feb/26',home:'León',hg:1,ag:0,away:'Tigres'},
{round:7,date:'21/feb/26',home:'Atl. San Luis',hg:3,ag:1,away:'Santos'},
{round:7,date:'22/feb/26',home:'Pachuca',hg:2,ag:1,away:'FC Juárez'},
{round:7,date:'22/feb/26',home:'Necaxa',hg:0,ag:1,away:'Querétaro'},
{round:7,date:'22/feb/26',home:'Mazatlán',hg:0,ag:0,away:'Tijuana'},
{round:7,date:'22/feb/26',home:'Monterrey',hg:0,ag:1,away:'Puebla'},
{round:8,date:'27/feb/26',home:'Pumas',hg:2,ag:1,away:'Toluca'},
{round:8,date:'27/feb/26',home:'Guadalajara',hg:2,ag:1,away:'León'},
{round:8,date:'28/feb/26',home:'Santos',hg:1,ag:2,away:'Cruz Azul'},
{round:8,date:'28/feb/26',home:'Atlas',hg:1,ag:2,away:'América'},
{round:8,date:'28/feb/26',home:'Querétaro',hg:1,ag:1,away:'Atl. San Luis'},
{round:8,date:'01/mar/26',home:'Tijuana',hg:0,ag:1,away:'Pachuca'},
{round:8,date:'01/mar/26',home:'Tigres',hg:2,ag:1,away:'Monterrey'},
{round:8,date:'01/mar/26',home:'Puebla',hg:0,ag:1,away:'Necaxa'},
{round:8,date:'01/mar/26',home:'FC Juárez',hg:1,ag:2,away:'Mazatlán'},
{round:9,date:'06/mar/26',home:'Toluca',hg:3,ag:2,away:'Cruz Azul'},
{round:9,date:'06/mar/26',home:'América',hg:1,ag:0,away:'Santos'},
{round:9,date:'07/mar/26',home:'León',hg:1,ag:1,away:'Querétaro'},
{round:9,date:'07/mar/26',home:'Pachuca',hg:2,ag:1,away:'Atlas'},
{round:9,date:'07/mar/26',home:'Atl. San Luis',hg:2,ag:1,away:'Pumas'},
{round:9,date:'08/mar/26',home:'Monterrey',hg:0,ag:1,away:'Guadalajara'},
{round:9,date:'08/mar/26',home:'Necaxa',hg:1,ag:2,away:'Tijuana'},
{round:9,date:'08/mar/26',home:'Mazatlán',hg:0,ag:2,away:'Tigres'},
{round:9,date:'08/mar/26',home:'Puebla',hg:1,ag:0,away:'FC Juárez'},
{round:10,date:'13/mar/26',home:'Santos',hg:0,ag:3,away:'Pumas'},
{round:10,date:'13/mar/26',home:'Cruz Azul',hg:2,ag:1,away:'León'},
{round:10,date:'14/mar/26',home:'Guadalajara',hg:3,ag:1,away:'Toluca'},
{round:10,date:'14/mar/26',home:'Atlas',hg:1,ag:1,away:'Necaxa'},
{round:10,date:'14/mar/26',home:'Querétaro',hg:0,ag:0,away:'América'},
{round:10,date:'14/mar/26',home:'FC Juárez',hg:2,ag:1,away:'Tigres'},
{round:10,date:'15/mar/26',home:'Tijuana',hg:1,ag:2,away:'Atl. San Luis'},
{round:10,date:'15/mar/26',home:'Pachuca',hg:2,ag:2,away:'Monterrey'},
{round:10,date:'15/mar/26',home:'Mazatlán',hg:0,ag:1,away:'Puebla'},
{round:11,date:'19/mar/26',home:'Pumas',hg:1,ag:0,away:'Guadalajara'},
{round:11,date:'20/mar/26',home:'Toluca',hg:2,ag:0,away:'Santos'},
{round:11,date:'20/mar/26',home:'León',hg:1,ag:1,away:'Pachuca'},
{round:11,date:'20/mar/26',home:'Tigres',hg:1,ag:1,away:'Atlas'},
{round:11,date:'20/mar/26',home:'América',hg:1,ag:0,away:'Mazatlán'},
{round:11,date:'21/mar/26',home:'Necaxa',hg:1,ag:1,away:'Cruz Azul'},
{round:11,date:'21/mar/26',home:'Atl. San Luis',hg:1,ag:1,away:'Querétaro'},
{round:11,date:'21/mar/26',home:'FC Juárez',hg:0,ag:1,away:'Tijuana'},
{round:11,date:'22/mar/26',home:'Puebla',hg:1,ag:2,away:'Monterrey'},
{round:12,date:'21/mar/26',home:'Monterrey',hg:2,ag:3,away:'Guadalajara'},
{round:12,date:'22/mar/26',home:'Pumas',hg:1,ag:0,away:'América'},
{round:12,date:'22/mar/26',home:'Cruz Azul',hg:1,ag:1,away:'Mazatlán'},
{round:12,date:'22/mar/26',home:'Santos',hg:0,ag:1,away:'Atl. San Luis'},
{round:12,date:'22/mar/26',home:'Atlas',hg:0,ag:0,away:'Querétaro'},
{round:12,date:'23/mar/26',home:'Toluca',hg:2,ag:2,away:'Pachuca'},
{round:12,date:'23/mar/26',home:'Tijuana',hg:1,ag:0,away:'Necaxa'},
{round:12,date:'23/mar/26',home:'FC Juárez',hg:0,ag:1,away:'Tigres'},
{round:12,date:'23/mar/26',home:'León',hg:0,ag:2,away:'Puebla'},
{round:13,date:'03/abr/26',home:'Puebla',hg:1,ag:1,away:'FC Juárez'},
{round:13,date:'03/abr/26',home:'Necaxa',hg:2,ag:1,away:'Mazatlán'},
{round:13,date:'03/abr/26',home:'Tijuana',hg:1,ag:0,away:'Tigres'},
{round:13,date:'04/abr/26',home:'Querétaro',hg:1,ag:0,away:'Toluca'},
{round:13,date:'04/abr/26',home:'Santos',hg:1,ag:1,away:'América'},
{round:13,date:'04/abr/26',home:'Pachuca',hg:2,ag:1,away:'Cruz Azul'},
{round:13,date:'04/abr/26',home:'León',hg:2,ag:0,away:'Atlas'},
{round:13,date:'04/abr/26',home:'Atl. San Luis',hg:2,ag:1,away:'Monterrey'},
{round:13,date:'05/abr/26',home:'Guadalajara',hg:2,ag:2,away:'Pumas'},
];


// ══════════════════════════════════════════
// PRÓXIMOS PARTIDOS — Clausura 2026
// Actualiza las fechas y agrega/quita partidos aquí
// ══════════════════════════════════════════
const UPCOMING = [
{round:14,date:'11/abr/26',home:'Puebla',away:'León'},
{round:14,date:'11/abr/26',home:'FC Juárez',away:'Tijuana'},
{round:14,date:'12/abr/26',home:'Querétaro',away:'Necaxa'},
{round:14,date:'12/abr/26',home:'Tigres',away:'Guadalajara'},
{round:14,date:'12/abr/26',home:'Atlas',away:'Monterrey'},
{round:14,date:'12/abr/26',home:'Pachuca',away:'Santos'},
{round:14,date:'12/abr/26',home:'América',away:'Cruz Azul'},
{round:14,date:'12/abr/26',home:'Pumas',away:'Mazatlán'},
{round:14,date:'13/abr/26',home:'Toluca',away:'Atl. San Luis'},
{round:15,date:'18/abr/26',home:'Atl. San Luis',away:'Pumas'},
{round:15,date:'18/abr/26',home:'Mazatlán',away:'Querétaro'},
{round:15,date:'18/abr/26',home:'Necaxa',away:'Tigres'},
{round:15,date:'19/abr/26',home:'Cruz Azul',away:'Tijuana'},
{round:15,date:'19/abr/26',home:'Monterrey',away:'Pachuca'},
{round:15,date:'19/abr/26',home:'Guadalajara',away:'Santos'},
{round:15,date:'19/abr/26',home:'León',away:'Atlas'},
{round:15,date:'19/abr/26',home:'FC Juárez',away:'Toluca'},
{round:15,date:'20/abr/26',home:'América',away:'Puebla'},
{round:16,date:'25/abr/26',home:'Santos',away:'FC Juárez'},
{round:16,date:'25/abr/26',home:'Tijuana',away:'Cruz Azul'},
{round:16,date:'25/abr/26',home:'Atlas',away:'Pumas'},
{round:16,date:'25/abr/26',home:'Monterrey',away:'Querétaro'},
{round:16,date:'26/abr/26',home:'Guadalajara',away:'León'},
{round:16,date:'26/abr/26',home:'Toluca',away:'Tigres'},
{round:16,date:'26/abr/26',home:'Pachuca',away:'América'},
{round:16,date:'26/abr/26',home:'Puebla',away:'Atl. San Luis'},
{round:16,date:'26/abr/26',home:'Necaxa',away:'Mazatlán'},
{round:17,date:'02/may/26',home:'León',away:'Monterrey'},
{round:17,date:'02/may/26',home:'Cruz Azul',away:'Guadalajara'},
{round:17,date:'02/may/26',home:'Querétaro',away:'Santos'},
{round:17,date:'02/may/26',home:'Pumas',away:'Necaxa'},
{round:17,date:'03/may/26',home:'Tigres',away:'Toluca'},
{round:17,date:'03/may/26',home:'América',away:'Tijuana'},
{round:17,date:'03/may/26',home:'Atl. San Luis',away:'Atlas'},
{round:17,date:'03/may/26',home:'Mazatlán',away:'Pachuca'},
{round:17,date:'03/may/26',home:'FC Juárez',away:'Puebla'},
];


// ══════════════════════════════════════════
// PARTIDOS AGREGADOS POR EL ADMIN
// (se llenan automáticamente al exportar)
// ══════════════════════════════════════════
const ACTUALIZACIONES = [
  // Pega aquí los resultados nuevos cuando uses "Exportar JSON"
  // Ejemplo:
  // {round:14, date:'12/abr/26', home:'América', hg:2, ag:1, away:'Cruz Azul'},
];
