// â•”â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•—
// â•‘  SCORE GUARDIANS â€” Clausura 2026                     â•‘
// â•‘  Datos verificados J1-J14 + PrÃ³ximos J15             â•‘
// â•šâ•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

const C2026 = [
  {round:1,date:'09/ene/26',home:'Mazatlán',hg:1,ag:2,away:'FC Juárez'},
  {round:1,date:'09/ene/26',home:'Atlas',hg:1,ag:0,away:'Puebla'},
  {round:1,date:'09/ene/26',home:'Tijuana',hg:0,ag:0,away:'América'},
  {round:1,date:'10/ene/26',home:'Guadalajara',hg:2,ag:0,away:'Pachuca'},
  {round:1,date:'10/ene/26',home:'León',hg:2,ag:1,away:'Cruz Azul'},
  {round:1,date:'10/ene/26',home:'Santos',hg:1,ag:3,away:'Necaxa'},
  {round:1,date:'10/ene/26',home:'Monterrey',hg:0,ag:1,away:'Toluca'},
  {round:1,date:'11/ene/26',home:'UNAM',hg:1,ag:1,away:'Querétaro'},
  {round:1,date:'11/ene/26',home:'Atl. San Luis',hg:1,ag:2,away:'Tigres'},
  {round:2,date:'13/ene/26',home:'Puebla',hg:2,ag:1,away:'Mazatlán'},
  {round:2,date:'13/ene/26',home:'Necaxa',hg:0,ag:2,away:'Monterrey'},
  {round:2,date:'13/ene/26',home:'Pachuca',hg:2,ag:1,away:'León'},
  {round:2,date:'13/ene/26',home:'FC Juárez',hg:0,ag:1,away:'Guadalajara'},
  {round:2,date:'14/ene/26',home:'Cruz Azul',hg:2,ag:0,away:'Atlas'},
  {round:2,date:'14/ene/26',home:'Querétaro',hg:1,ag:2,away:'Tijuana'},
  {round:2,date:'14/ene/26',home:'América',hg:0,ag:2,away:'Atl. San Luis'},
  {round:2,date:'14/ene/26',home:'Tigres',hg:0,ag:1,away:'UNAM'},
  {round:2,date:'14/ene/26',home:'Toluca',hg:3,ag:1,away:'Santos'},
  {round:3,date:'16/ene/26',home:'Mazatlán',hg:1,ag:5,away:'Monterrey'},
  {round:3,date:'17/ene/26',home:'Guadalajara',hg:2,ag:1,away:'Querétaro'},
  {round:3,date:'17/ene/26',home:'Necaxa',hg:0,ag:1,away:'Atlas'},
  {round:3,date:'17/ene/26',home:'Tigres',hg:0,ag:0,away:'Toluca'},
  {round:3,date:'17/ene/26',home:'Cruz Azul',hg:1,ag:0,away:'Puebla'},
  {round:3,date:'17/ene/26',home:'Tijuana',hg:1,ag:1,away:'Atl. San Luis'},
  {round:3,date:'18/ene/26',home:'UNAM',hg:1,ag:1,away:'León'},
  {round:3,date:'18/ene/26',home:'Santos',hg:2,ag:2,away:'FC Juárez'},
  {round:3,date:'18/ene/26',home:'Pachuca',hg:0,ag:0,away:'América'},
  {round:4,date:'30/ene/26',home:'Puebla',hg:0,ag:0,away:'Toluca'},
  {round:4,date:'30/ene/26',home:'UNAM',hg:4,ag:0,away:'Santos'},
  {round:4,date:'30/ene/26',home:'FC Juárez',hg:3,ag:4,away:'Cruz Azul'},
  {round:4,date:'31/ene/26',home:'Atlas',hg:1,ag:0,away:'Mazatlán'},
  {round:4,date:'31/ene/26',home:'Atl. San Luis',hg:2,ag:3,away:'Guadalajara'},
  {round:4,date:'31/ene/26',home:'Monterrey',hg:2,ag:2,away:'Tijuana'},
  {round:4,date:'31/ene/26',home:'León',hg:1,ag:2,away:'Tigres'},
  {round:4,date:'31/ene/26',home:'América',hg:2,ag:0,away:'Necaxa'},
  {round:4,date:'01/feb/26',home:'Querétaro',hg:0,ag:0,away:'Pachuca'},
  {round:5,date:'06/feb/26',home:'Tigres',hg:5,ag:1,away:'Santos'},
  {round:5,date:'06/feb/26',home:'Necaxa',hg:4,ag:1,away:'Atl. San Luis'},
  {round:5,date:'06/feb/26',home:'Tijuana',hg:0,ag:0,away:'Puebla'},
  {round:5,date:'06/feb/26',home:'Mazatlán',hg:1,ag:2,away:'Guadalajara'},
  {round:5,date:'07/feb/26',home:'Querétaro',hg:2,ag:0,away:'León'},
  {round:5,date:'07/feb/26',home:'Toluca',hg:1,ag:1,away:'Cruz Azul'},
  {round:5,date:'07/feb/26',home:'Atlas',hg:2,ag:2,away:'UNAM'},
  {round:5,date:'07/feb/26',home:'Pachuca',hg:2,ag:0,away:'FC Juárez'},
  {round:5,date:'07/feb/26',home:'América',hg:1,ag:0,away:'Monterrey'},
  {round:6,date:'13/feb/26',home:'Puebla',hg:2,ag:3,away:'UNAM'},
  {round:6,date:'13/feb/26',home:'Toluca',hg:1,ag:0,away:'Tijuana'},
  {round:6,date:'14/feb/26',home:'Atl. San Luis',hg:3,ag:0,away:'Querétaro'},
  {round:6,date:'14/feb/26',home:'Pachuca',hg:3,ag:1,away:'Atlas'},
  {round:6,date:'14/feb/26',home:'Monterrey',hg:1,ag:0,away:'León'},
  {round:6,date:'14/feb/26',home:'FC Juárez',hg:1,ag:2,away:'Necaxa'},
  {round:6,date:'14/feb/26',home:'Guadalajara',hg:1,ag:0,away:'América'},
  {round:6,date:'15/feb/26',home:'Cruz Azul',hg:2,ag:1,away:'Tigres'},
  {round:6,date:'15/feb/26',home:'Santos',hg:1,ag:2,away:'Mazatlán'},
  {round:7,date:'20/feb/26',home:'Tigres',hg:1,ag:2,away:'Pachuca'},
  {round:7,date:'20/feb/26',home:'Puebla',hg:0,ag:4,away:'América'},
  {round:7,date:'21/feb/26',home:'Atlas',hg:3,ag:2,away:'Atl. San Luis'},
  {round:7,date:'21/feb/26',home:'León',hg:2,ag:1,away:'Santos'},
  {round:7,date:'21/feb/26',home:'Necaxa',hg:0,ag:3,away:'Toluca'},
  {round:7,date:'21/feb/26',home:'Cruz Azul',hg:2,ag:1,away:'Guadalajara'},
  {round:7,date:'21/feb/26',home:'Tijuana',hg:1,ag:1,away:'Mazatlán'},
  {round:7,date:'22/feb/26',home:'UNAM',hg:2,ag:0,away:'Monterrey'},
  {round:7,date:'07/abr/26',home:'Querétaro',hg:1,ag:1,away:'FC Juárez'},
  {round:8,date:'27/feb/26',home:'Mazatlán',hg:1,ag:0,away:'Pachuca'},
  {round:8,date:'27/feb/26',home:'Querétaro',hg:2,ag:2,away:'Santos'},
  {round:8,date:'27/feb/26',home:'FC Juárez',hg:3,ag:1,away:'Atlas'},
  {round:8,date:'27/feb/26',home:'Tijuana',hg:1,ag:1,away:'UNAM'},
  {round:8,date:'28/feb/26',home:'Atl. San Luis',hg:0,ag:1,away:'Puebla'},
  {round:8,date:'28/feb/26',home:'Toluca',hg:2,ag:0,away:'Guadalajara'},
  {round:8,date:'28/feb/26',home:'Monterrey',hg:0,ag:2,away:'Cruz Azul'},
  {round:8,date:'28/feb/26',home:'León',hg:2,ag:1,away:'Necaxa'},
  {round:8,date:'28/feb/26',home:'América',hg:1,ag:4,away:'Tigres'},
  {round:9,date:'03/mar/26',home:'Pachuca',hg:2,ag:1,away:'Necaxa'},
  {round:9,date:'03/mar/26',home:'Santos',hg:1,ag:2,away:'Cruz Azul'},
  {round:9,date:'03/mar/26',home:'Atl. San Luis',hg:4,ag:1,away:'Mazatlán'},
  {round:9,date:'03/mar/26',home:'UNAM',hg:2,ag:3,away:'Toluca'},
  {round:9,date:'04/mar/26',home:'Monterrey',hg:4,ag:0,away:'Querétaro'},
  {round:9,date:'04/mar/26',home:'Puebla',hg:3,ag:1,away:'Tigres'},
  {round:9,date:'04/mar/26',home:'Atlas',hg:2,ag:1,away:'Tijuana'},
  {round:9,date:'04/mar/26',home:'América',hg:1,ag:2,away:'FC Juárez'},
  {round:9,date:'18/mar/26',home:'Guadalajara',hg:5,ag:0,away:'León'},
  {round:10,date:'06/mar/26',home:'Mazatlán',hg:4,ag:2,away:'León'},
  {round:10,date:'06/mar/26',home:'Necaxa',hg:0,ag:1,away:'UNAM'},
  {round:10,date:'07/mar/26',home:'Cruz Azul',hg:3,ag:0,away:'Atl. San Luis'},
  {round:10,date:'07/mar/26',home:'Querétaro',hg:1,ag:2,away:'América'},
  {round:10,date:'07/mar/26',home:'Pachuca',hg:2,ag:1,away:'Puebla'},
  {round:10,date:'07/mar/26',home:'Atlas',hg:1,ag:2,away:'Guadalajara'},
  {round:10,date:'07/mar/26',home:'Tigres',hg:1,ag:0,away:'Monterrey'},
  {round:10,date:'08/mar/26',home:'Toluca',hg:3,ag:1,away:'FC Juárez'},
  {round:10,date:'08/mar/26',home:'Tijuana',hg:1,ag:2,away:'Santos'},
  {round:11,date:'13/mar/26',home:'Puebla',hg:0,ag:0,away:'Necaxa'},
  {round:11,date:'13/mar/26',home:'FC Juárez',hg:2,ag:2,away:'Monterrey'},
  {round:11,date:'14/mar/26',home:'Atl. San Luis',hg:1,ag:1,away:'Pachuca'},
  {round:11,date:'14/mar/26',home:'Guadalajara',hg:3,ag:0,away:'Santos'},
  {round:11,date:'14/mar/26',home:'León',hg:0,ag:3,away:'Tijuana'},
  {round:11,date:'14/mar/26',home:'Toluca',hg:1,ag:1,away:'Atlas'},
  {round:11,date:'14/mar/26',home:'UNAM',hg:2,ag:2,away:'Cruz Azul'},
  {round:11,date:'15/mar/26',home:'Tigres',hg:0,ag:0,away:'Querétaro'},
  {round:11,date:'15/mar/26',home:'América',hg:2,ag:0,away:'Mazatlán'},
  {round:12,date:'20/mar/26',home:'Necaxa',hg:3,ag:0,away:'Tijuana'},
  {round:12,date:'20/mar/26',home:'Mazatlán',hg:1,ag:1,away:'Cruz Azul'},
  {round:12,date:'21/mar/26',home:'Atlas',hg:0,ag:0,away:'Querétaro'},
  {round:12,date:'21/mar/26',home:'Atl. San Luis',hg:1,ag:2,away:'León'},
  {round:12,date:'21/mar/26',home:'Monterrey',hg:2,ag:3,away:'Guadalajara'},
  {round:12,date:'21/mar/26',home:'UNAM',hg:1,ag:0,away:'América'},
  {round:12,date:'22/mar/26',home:'Pachuca',hg:1,ag:1,away:'Toluca'},
  {round:12,date:'22/mar/26',home:'Santos',hg:2,ag:1,away:'Puebla'},
  {round:12,date:'22/mar/26',home:'FC Juárez',hg:2,ag:1,away:'Tigres'},
  {round:13,date:'03/abr/26',home:'Puebla',hg:1,ag:1,away:'FC Juárez'},
  {round:13,date:'03/abr/26',home:'Necaxa',hg:2,ag:1,away:'Mazatlán'},
  {round:13,date:'03/abr/26',home:'Tijuana',hg:1,ag:0,away:'Tigres'},
  {round:13,date:'04/abr/26',home:'Monterrey',hg:1,ag:2,away:'Atl. San Luis'},
  {round:13,date:'04/abr/26',home:'Querétaro',hg:1,ag:0,away:'Toluca'},
  {round:13,date:'04/abr/26',home:'León',hg:2,ag:0,away:'Atlas'},
  {round:13,date:'04/abr/26',home:'Cruz Azul',hg:1,ag:2,away:'Pachuca'},
  {round:13,date:'04/abr/26',home:'Santos',hg:1,ag:1,away:'América'},
  {round:13,date:'05/abr/26',home:'Guadalajara',hg:2,ag:2,away:'UNAM'},
  {round:14,date:'11/abr/26',home:'Puebla',hg:0,ag:1,away:'León'},
  {round:14,date:'11/abr/26',home:'FC Juárez',hg:1,ag:2,away:'Tijuana'},
  {round:14,date:'12/abr/26',home:'Querétaro',hg:3,ag:1,away:'Necaxa'},
  {round:14,date:'12/abr/26',home:'Tigres',hg:4,ag:1,away:'Guadalajara'},
  {round:14,date:'12/abr/26',home:'Atlas',hg:0,ag:0,away:'Monterrey'},
  {round:14,date:'12/abr/26',home:'Pachuca',hg:4,ag:2,away:'Santos'},
  {round:14,date:'12/abr/26',home:'América',hg:1,ag:1,away:'Cruz Azul'},
  {round:14,date:'12/abr/26',home:'UNAM',hg:3,ag:1,away:'Mazatlán'},
  {round:14,date:'13/abr/26',home:'Toluca',hg:1,ag:1,away:'Atl. San Luis'},
  {round:15,date:'17/abr/26',home:'Atl. San Luis',hg:0,ag:2,away:'UNAM'},
  {round:15,date:'17/abr/26',home:'Mazatlán',hg:1,ag:1,away:'Querétaro'},
  {round:15,date:'18/abr/26',home:'Necaxa',hg:1,ag:1,away:'Tigres'},
  {round:15,date:'18/abr/26',home:'Cruz Azul',hg:1,ag:1,away:'Tijuana'},
  {round:15,date:'18/abr/26',home:'Monterrey',hg:1,ag:3,away:'Pachuca'},
  {round:15,date:'18/abr/26',home:'Guadalajara',hg:5,ag:0,away:'Puebla'},
  {round:15,date:'18/abr/26',home:'León',hg:3,ag:1,away:'FC Juárez'},
  {round:15,date:'18/abr/26',home:'América',hg:2,ag:1,away:'Toluca'},
  {round:15,date:'19/abr/26',home:'Santos',hg:0,ag:1,away:'Atlas'},
  {round:16,date:'21/abr/26',home:'Querétaro',hg:1,ag:1,away:'Cruz Azul'},
  {round:16,date:'21/abr/26',home:'UNAM',hg:4,ag:2,away:'FC Juárez'},
  {round:16,date:'21/abr/26',home:'León',hg:2,ag:3,away:'América'},
  {round:16,date:'21/abr/26',home:'Monterrey',hg:2,ag:1,away:'Puebla'}
];

const UPCOMING = [
  {round:16,date:'22/abr/26',home:'Atlas',away:'Tigres'},
  {round:16,date:'22/abr/26',home:'Atl. San Luis',away:'Santos'},
  {round:16,date:'22/abr/26',home:'Mazatlán',away:'Toluca'},
  {round:16,date:'22/abr/26',home:'Necaxa',away:'Guadalajara'},
  {round:16,date:'22/abr/26',home:'Tijuana',away:'Pachuca'},
  {round:17,date:'24/abr/26',home:'Puebla',away:'Querétaro'},
  {round:17,date:'25/abr/26',home:'Pachuca',away:'UNAM'},
  {round:17,date:'25/abr/26',home:'Tigres',away:'Mazatlán'},
  {round:17,date:'25/abr/26',home:'Guadalajara',away:'Tijuana'},
  {round:17,date:'25/abr/26',home:'Toluca',away:'León'},
  {round:17,date:'25/abr/26',home:'América',away:'Atlas'},
  {round:17,date:'25/abr/26',home:'FC Juárez',away:'Atl. San Luis'},
  {round:17,date:'26/abr/26',home:'Santos',away:'Monterrey'},
  {round:17,date:'26/abr/26',home:'Cruz Azul',away:'Necaxa'}
];

const ACTUALIZACIONES = [];





